[package]
license = "MIT"
name = "util-tests"
repository = "https://github.com/DiamondLovesYou/pnacl-clang-driver"
version = "0.0.0"

[dependencies]
lazy_static = "*"
regex = "*"

[dependencies.util]
path = "../util"

[lib]
name = "util_tests"
path = "lib.rs"
